"use client";

import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { useLanguage } from "@/hooks/useLanguage";
import { translations } from "@/lib/translations";

export default function LegalPage() {
  const lang = useLanguage();
const t = translations[lang as "en" | "zu" | "af" | "fr"];
  return (
    <div className="min-h-screen bg-background px-6 py-20">

      {/* NAV */}
      <div className="max-w-6xl mx-auto mb-10 flex justify-start items-center">
        <Link href="/">
          <Button variant="outline">{t.backToPlatform}</Button>
        </Link>
      </div>

      {/* HERO */}
      <div className="max-w-6xl mx-auto text-center mb-20">
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-5xl font-bold mb-6"
        >
          Legal & Platform Use Notice
        </motion.h1>

        <p className="text-lg text-muted-foreground max-w-2xl mx-auto mb-8">
          Important information regarding the use of this platform, including responsibilities, limitations, and general legal considerations.
        </p>

        <div className="flex justify-center gap-4">
          <Link href="/portal">
            <Button size="lg">Access Platform</Button>
          </Link>

          <Link href="/pricing">
            <Button variant="outline" size="lg">
              View Pricing
            </Button>
          </Link>
        </div>
      </div>

      {/* SECTION GRID */}
      <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-8">

        {/* SECTION 1 */}
        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }}>
          <Card className="p-6 rounded-2xl shadow">
            <CardContent>
              <h3 className="text-xl font-semibold mb-3">
                General Use of the Platform
              </h3>
              <p className="text-muted-foreground">
                This platform provides tools intended to support engineering, operational, and analytical workflows.
                <br /><br />
                Use of the platform is subject to applicable laws, regulations, and internal policies of the user’s organization.
              </p>
            </CardContent>
          </Card>
        </motion.div>

        {/* SECTION 2 */}
        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }}>
          <Card className="p-6 rounded-2xl shadow">
            <CardContent>
              <h3 className="text-xl font-semibold mb-3">
                No Professional Advice
              </h3>
              <p className="text-muted-foreground">
                Information and outputs provided by the platform are for informational and support purposes only.
                <br /><br />
                They do not constitute professional engineering, legal, or regulatory advice and should not be relied upon as such.
              </p>
            </CardContent>
          </Card>
        </motion.div>

        {/* SECTION 3 */}
        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }}>
          <Card className="p-6 rounded-2xl shadow">
            <CardContent>
              <h3 className="text-xl font-semibold mb-3">
                Limitation of Liability
              </h3>
              <p className="text-muted-foreground">
                To the extent permitted by law, the platform and its providers shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use of, or inability to use, the platform.
                <br /><br />
                This includes reliance on any outputs, data, or insights generated by the system.
              </p>
            </CardContent>
          </Card>
        </motion.div>

        {/* SECTION 4 */}
        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }}>
          <Card className="p-6 rounded-2xl shadow">
            <CardContent>
              <h3 className="text-xl font-semibold mb-3">
                User Responsibility
              </h3>
              <p className="text-muted-foreground">
                Users are responsible for verifying all outputs, ensuring compliance with applicable standards and regulations, and making final decisions based on their professional judgment.
                <br /><br />
                The platform is intended to support — not replace — qualified expertise.
              </p>
            </CardContent>
          </Card>
        </motion.div>

      </div>

      {/* SECTION 5 */}
      <div className="max-w-4xl mx-auto mt-24">
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}>
          <Card className="p-6 rounded-2xl shadow">
            <CardContent>
              <h3 className="text-xl font-semibold mb-3">
                Availability & Service
              </h3>
              <p className="text-muted-foreground">
                The platform is provided on an “as is” and “as available” basis without warranties of any kind, express or implied.
                <br /><br />
                Availability, performance, and functionality may change over time and are not guaranteed.
              </p>
            </CardContent>
          </Card>
        </motion.div>
      </div>

      {/* LEGAL DISCLAIMER */}
      <div className="max-w-4xl mx-auto mt-24">
        <Card className="p-6 rounded-2xl border border-border">
          <CardContent>
            <h3 className="text-xl font-semibold mb-3">
              Important Notice
            </h3>
            <p className="text-muted-foreground text-sm">
              By using this platform, users acknowledge that it provides support tools only and does not replace professional judgment, certified review processes, or regulatory compliance requirements.
              <br /><br />
              Users accept full responsibility for verifying outputs, ensuring compliance, and making all final decisions.
            </p>
          </CardContent>
        </Card>
      </div>

      {/* FINAL CTA */}
      <div className="text-center mt-24">
        <h3 className="text-3xl font-semibold mb-4">
          Use the Platform Responsibly
        </h3>

        <p className="text-muted-foreground mb-6">
          Access AI-assisted tools designed to support engineering and operational workflows.
        </p>

        <div className="flex justify-center gap-4">
          <Link href="/portal">
            <Button size="lg">Start Free</Button>
          </Link>

          <Link href="/pricing">
            <Button variant="outline" size="lg">
              View Pricing
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
}